version: '3'

services:
  react:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - node
      - django
  node:
    build: ./backend-node
    ports:
      - 8084:8084
    env_file:
      - ./backend-node/.env
  django:
    build: ./backend-django
    ports:
      - 8085:8085
    env_file:
      - ./backend-django/app/.env
