export const cancersRows = [
  { id: 1, abbreviations: 'BRCA', full_name: 'Breast cancer' },
  { id: 2, abbreviations: 'CCC', full_name: 'Cholangiocarcinoma' },
  { id: 3, abbreviations: 'CLL', full_name: 'Chronic lymphocytic leukemia' },
  { id: 4, abbreviations: 'CRC', full_name: 'Colorectal cancer' },
  { id: 5, abbreviations: 'DLBC', full_name: 'Diffuse large B-cell lymphoma' },
  { id: 6, abbreviations: 'EAC', full_name: 'Esophageal Adenocarcinoma' },
  { id: 7, abbreviations: 'EC', full_name: 'Endometrial Cancer' },
  { id: 8, abbreviations: 'ESCC', full_name: 'Esophageal squamous-cell carcinoma' },
  { id: 9, abbreviations: 'GBM', full_name: 'Glioblastoma' },
  { id: 10, abbreviations: 'GC', full_name: 'Gastric Cancer' },
  { id: 11, abbreviations: 'HL', full_name: 'Hodgkin Lymphoma' },
  { id: 12, abbreviations: 'HNC', full_name: 'Head and Neck Cancer' },
  { id: 13, abbreviations: 'KIRC', full_name: 'Kidney renal clear cell carcinoma' },
  { id: 14, abbreviations: 'LAML', full_name: 'Acute myeloid leukemia' },
  { id: 15, abbreviations: 'LCC', full_name: 'Left Colorectal Cancer' },
  { id: 16, abbreviations: 'LIHC', full_name: 'Liver Hepatocellular Carcinoma' },
  { id: 17, abbreviations: 'LUCA', full_name: 'Lung cancer' },
  { id: 18, abbreviations: 'MB', full_name: 'Medulloblastoma' },
  { id: 19, abbreviations: 'MEL', full_name: 'Melanoma' },
  { id: 20, abbreviations: 'MM', full_name: 'Multiple Myeloma' },
  { id: 21, abbreviations: 'PAAD', full_name: 'Pancreatic adenocarcinoma' },
  { id: 22, abbreviations: 'PDAC', full_name: 'Pancreatic ductal adenocarcinoma' },
  { id: 23, abbreviations: 'PRAD', full_name: 'Prostate Adenocarcinoma' },
  { id: 24, abbreviations: 'THCA', full_name: 'Thyroid Cancer' },
];

export const otherRows = [
  { id: 1, abbreviations: 'AP', full_name: 'Angina Pectoris' },
  { id: 2, abbreviations: 'AS', full_name: 'Atherosclerosis' },
  { id: 3, abbreviations: 'BD', full_name: 'Bowel Disease' },
  { id: 4, abbreviations: 'BLL', full_name: 'Benign Liver Lesions' },
  { id: 5, abbreviations: 'CD', full_name: 'Crohn\'s Disease' },
  { id: 6, abbreviations: 'CEC', full_name: 'Circulating Epithelial Cells' },
  { id: 7, abbreviations: 'CHB', full_name: 'Chronic Hepatitis B Virus' },
  { id: 8, abbreviations: 'CLD', full_name: 'Chronic Liver Disease' },
  { id: 9, abbreviations: 'CP', full_name: 'Chronic Pancreatitis' },
  { id: 10, abbreviations: 'CT', full_name: 'control' },
  { id: 11, abbreviations: 'DS', full_name: 'corresponding disease' },
  { id: 12, abbreviations: 'E', full_name: 'Epilepsy' },
  { id: 13, abbreviations: 'GH', full_name: 'Hematuria' },
  { id: 14, abbreviations: 'HBVC', full_name: 'HBV Carrier' },
  { id: 15, abbreviations: 'HBVLC', full_name: 'HBV Cirrhosis' },
  { id: 16, abbreviations: 'HC', full_name: 'healthy' },
  { id: 17, abbreviations: 'HP', full_name: 'Hydrocephalus Patient' },
  { id: 18, abbreviations: 'LC', full_name: 'Liver Cirrhosis' },
  { id: 19, abbreviations: 'MS', full_name: 'Multiple Sclerosis' },
  { id: 20, abbreviations: 'nSTEMI', full_name: 'Non-ST-Elevation Myocardial Infarction' },
  { id: 21, abbreviations: 'PD', full_name: 'Pancreatic Disease' },
  { id: 22, abbreviations: 'PH', full_name: 'Pulmonary Hypertension' },
  { id: 23, abbreviations: 'SAP', full_name: 'Stable Angina Pectoris' },
  { id: 24, abbreviations: 'UAP', full_name: 'Unstable Angina Pectoris' },
  { id: 25, abbreviations: 'UC', full_name: 'Ulcerative Colitis' },
];

export const valuesRows = [
  { id: 1, abbreviations: '15t5', full_name: 'promoter-150TSS50' },
  { id: 2, abbreviations: '31e1', full_name: 'promoter300100exon1end' },
  { id: 3, abbreviations: 'splc', full_name: 'splicing' },
  { id: 4, abbreviations: 'expr', full_name: 'expression' },
  { id: 5, abbreviations: 'te', full_name: 'transposable element' },
  { id: 6, abbreviations: 'no', full_name: 'nucleosome occupancy' },
  { id: 7, abbreviations: 'noratio', full_name: 'nucleosome occupancy ratio' },
  { id: 8, abbreviations: 'rbc', full_name: 'red blood cell' },
  { id: 9, abbreviations: 'area', full_name: 'Area of Peak' },
  { id: 10, abbreviations: 'itst', full_name: 'Intensity' },
  { id: 11, abbreviations: 'iclv', full_name: 'IncLevel' },
  { id: 12, abbreviations: 'CSF', full_name: 'Cerebrospinal Fluid' },
  { id: 13, abbreviations: 'PBMC', full_name: 'Peripheral Blood Mononuclear Cell' },
  { id: 14, abbreviations: 'EV', full_name: 'Extracellular vesicles' },
  { id: 15, abbreviations: 'TEP', full_name: 'Tumor-educated Platelets' },
  { id: 16, abbreviations: 'CEC', full_name: 'Circulating Epithelial Cells' },
  { id: 17, abbreviations: 'CTC', full_name: 'Circlulating Tumour Cells' },
];
